# Generated by Django 2.2 on 2019-12-28 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User_info',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=200)),
                ('user_pwd', models.CharField(max_length=2000)),
                ('join_time', models.DateTimeField(auto_now=True)),
                ('user_email', models.EmailField(max_length=254)),
                ('user_phone', models.CharField(max_length=20, null=True)),
                ('user_addr', models.CharField(max_length=100, null=True)),
                ('user_work', models.CharField(max_length=100, null=True)),
                ('user_hobby', models.CharField(max_length=300, null=True)),
                ('user_url', models.URLField(null=True)),
                ('user_gitHub', models.URLField(null=True)),
            ],
            options={
                'db_table': 'user_info',
            },
        ),
    ]
