# Generated by Django 2.2 on 2020-04-21 09:43

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('blog_User', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('article_id', models.AutoField(primary_key=True, serialize=False)),
                ('article_title', models.CharField(max_length=200)),
                ('article_outline', models.CharField(max_length=2000)),
                ('article_content', tinymce.models.HTMLField()),
                ('article_tag', models.CharField(max_length=200)),
                ('create_time', models.DateTimeField(default=datetime.datetime(2020, 4, 21, 9, 43, 15, 440406, tzinfo=utc))),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('read_count', models.IntegerField(default=0)),
                ('Fabulous_count', models.IntegerField(default=0)),
                ('not_Fabulous', models.IntegerField(default=0)),
                ('article_type', models.BooleanField(default=True)),
                ('article_url', models.CharField(blank=True, max_length=200, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog_User.User_info')),
            ],
            options={
                'db_table': 'Article_list',
                'ordering': ('-create_time',),
            },
        ),
    ]
