# Generated by Django 2.2 on 2019-12-28 10:22

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('blog_User', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('article_id', models.AutoField(primary_key=True, serialize=False)),
                ('article_title', models.CharField(max_length=200)),
                ('article_outline', models.CharField(max_length=2000)),
                ('article_content', models.TextField()),
                ('article_tag', models.CharField(max_length=200)),
                ('create_time', models.DateTimeField(verbose_name=datetime.datetime(2019, 12, 28, 10, 22, 0, 172007, tzinfo=utc))),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('read_count', models.CharField(default=0, max_length=200)),
                ('Fabulous_count', models.CharField(default=0, max_length=200)),
                ('not_Fabulous', models.CharField(default=0, max_length=200)),
                ('article_type', models.BooleanField(default=True)),
                ('article_url', models.CharField(max_length=200, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog_User.User_info')),
            ],
            options={
                'db_table': 'Article_list',
                'ordering': ('-create_time',),
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('create_time', models.DateTimeField(verbose_name=datetime.datetime(2019, 12, 28, 10, 22, 0, 173004, tzinfo=utc))),
                ('comment_content', models.TextField()),
                ('comment_Fabulous', models.CharField(default=0, max_length=200)),
                ('comment_not_Fabulous', models.CharField(default=0, max_length=200)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Article.Article')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog_User.User_info')),
            ],
        ),
    ]
