# Generated by Django 2.2 on 2020-04-21 09:50

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Article', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='create_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 21, 9, 50, 11, 516993, tzinfo=utc)),
        ),
    ]
