# Generated by Django 2.2 on 2020-04-20 07:46

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Article', '0003_auto_20200420_1121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='Fabulous_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='article',
            name='create_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 20, 7, 46, 18, 90989, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='article',
            name='not_Fabulous',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='article',
            name='read_count',
            field=models.IntegerField(default=0),
        ),
    ]
