# Generated by Django 2.2 on 2020-04-21 14:36

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Article', '0003_auto_20200421_1804'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='create_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 21, 14, 36, 19, 548691, tzinfo=utc)),
        ),
    ]
