# Generated by Django 2.2 on 2020-04-22 06:43

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Article', '0004_auto_20200421_2236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='create_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 22, 6, 43, 0, 465718, tzinfo=utc)),
        ),
    ]
