# Generated by Django 2.2 on 2020-04-22 16:32

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Article', '0006_auto_20200422_1458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='create_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 22, 16, 32, 8, 195342, tzinfo=utc)),
        ),
    ]
