# Generated by Django 2.2 on 2020-04-23 06:18

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Article', '0007_auto_20200423_0032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='create_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 23, 6, 18, 26, 645004, tzinfo=utc)),
        ),
    ]
