# Generated by Django 2.2 on 2020-04-28 08:28

import ckeditor.fields
import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Article', '0008_auto_20200423_1418'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='article_content',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='article',
            name='create_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 28, 8, 28, 24, 640348, tzinfo=utc)),
        ),
    ]
