# Generated by Django 2.2 on 2020-04-30 06:17

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Article', '0009_auto_20200428_1628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='create_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 30, 6, 17, 57, 331794, tzinfo=utc)),
        ),
    ]
