# Generated by Django 2.2 on 2020-05-16 07:49

import ckeditor_uploader.fields
import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Article', '0010_auto_20200430_1417'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='article_content',
            field=ckeditor_uploader.fields.RichTextUploadingField(default='', verbose_name='博文正文'),
        ),
        migrations.AlterField(
            model_name='article',
            name='create_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 16, 7, 49, 24, 271801, tzinfo=utc)),
        ),
    ]
