# Generated by Django 2.2 on 2020-05-16 08:29

import ckeditor.fields
import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Article', '0011_auto_20200516_1549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='article_content',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='article',
            name='create_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 16, 8, 29, 41, 709111, tzinfo=utc)),
        ),
    ]
