# Generated by Django 2.2 on 2020-05-16 09:23

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Article', '0012_auto_20200516_1629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='create_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 16, 9, 23, 34, 261202, tzinfo=utc)),
        ),
    ]
